### PR TITLE
Update to KDE Sdk 5.14, and quazip

### PR DESCRIPTION
**Pull request by corecontingency**

### CODE REVIEW

**Comment by corecontingency** [comment]
Fails installing with 

```
[user@mycomputer ~]$ flatpak install --user https://dl.flathub.org/build-repo/16169/org.keepassxc.KeePassXC.flatpakref

org.keepassxc.KeePassXC permissions:
    ipc     network     ssh-auth    wayland    x11    devices    file access [1]    dbus access [2]

    [1] /tmp, host, xdg-config/BraveSoftware/Brave-Browser/NativeMessagingHosts:create, xdg-config/chromium/NativeMessagingHosts:create, xdg-config/google-chrome/NativeMessagingHosts:create, xdg-config/kdeglobals:ro,
        xdg-config/vivaldi/NativeMessagingHosts:create, ~/.mozilla/native-messaging-hosts:create, ~/.tor-browser/app/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts:create
    [2] com.canonical.AppMenu.Registrar, com.canonical.Unity.Session, org.freedesktop.Notifications, org.freedesktop.ScreenSaver, org.freedesktop.login1.Manager, org.freedesktop.login1.Session, org.gnome.ScreenSaver,
        org.gnome.SessionManager, org.gnome.SessionManager.Presence, org.kde.StatusNotifierWatcher


        ID                                Branch           Op           Remote                     Download
 1. [✗] org.keepassxc.KeePassXC           test             i            keepassxc-origin           1.0 kB / 11.5 MB

Error: Failed to read commit 0cd4b7c4da9714b17abc16030ea546fc98523811b4aa32a2a587816888728cca: No such metadata object 4ca54e5841bd21319f87a90fe5ab371556d8077cd6d8cbf4151b2cf280c2b881.dirtree
error: Failed to install org.keepassxc.KeePassXC: Failed to read commit 0cd4b7c4da9714b17abc16030ea546fc98523811b4aa32a2a587816888728cca: No such metadata object 4ca54e5841bd21319f87a90fe5ab371556d8077cd6d8cbf4151b2cf280c2b881.dirtree
````

I think this is an issue with flatpak / os-tree. Let me try building this again.

bot, build

**Comment by corecontingency** [comment]
`flatpak install --user --ostree-verbose https://dl.flathub.org/build-repo/16169/org.keepassxc.KeePassXC.flatpakref`

shows
```

Proceed with these changes to the user installation? [Y/n]: y
Installing…                                                                                                            F: Preparing transaction in repository 0x5634ed32c3e0
F: Pushing lock non-blocking with timeout 30
F: Creating repo lock table
F: Opening repo lock file
F: Push lock: state=unlocked, depth=0
F: Locking repo shared
F: Using new tmpdir staging-b48a4100-0d64-42ee-bb1b-3b719020e4a2-SGDUnv
F: Loaded keepassxc-origin summary from cache
F: Adding GPG keyring data from keepassxc-origin.trustedkeys.gpg to verifier
F: GnuPG >= 2.1.17, skipping gpg-agent cleanup in /tmp/ostree-gpg-Wxp3Gh
F: starting fetch of 0cd4b7c4da9714b17abc16030ea546fc98523811b4aa32a2a587816888728cca.commit (detached)

Installing…                        0%F: fetch of 0cd4b7c4da9714b17abc16030ea546fc98523811b4aa32a2a587816888728cca.commit (detached) complete
F: _ostree_fetcher_should_retry_request: error: unset, n_retries_remaining: 5
F: Adding GPG keyring data from keepassxc-origin.trustedkeys.gpg to verifier
F: GnuPG >= 2.1.17, skipping gpg-agent cleanup in /tmp/ostree-gpg-HnzThj
F: pull: idle, exiting mainloop
F: Committing transaction in repository 0x5634ed32c3e0
F: txn commit staging-b48a4100-0d64-42ee-bb1b-3b719020e4a2-SGDUnv
F: Popping lock non-blocking with timeout 30
F: Pop lock: state=shared, depth=1
F: Unlocking repo

Error: Failed to read commit 0cd4b7c4da9714b17abc16030ea546fc98523811b4aa32a2a587816888728cca: No such metadata object 4ca54e5841bd21319f87a90fe5ab371556d8077cd6d8cbf4151b2cf280c2b881.dirtree
F: Free lock: state=unlocked, depth=0
F: Closing repo lock file
F: Free lock table
error: Failed to install org.keepassxc.KeePassXC: Failed to read commit 0cd4b7c4da9714b17abc16030ea546fc98523811b4aa32a2a587816888728cca: No such metadata object 4ca54e5841bd21319f87a90fe5ab371556d8077cd6d8cbf4151b2cf280c2b881.dirtree
```

**Comment by corecontingency** [comment]
Rebooted my computer, and now I can install the flatpak. I works fine, no issues that I see. Running on Arch with GNOME on Xorg.

Maybe it was a corrupted cached copy of the flatpak it was trying to install? That was weird.

**Comment by eszlari** [comment]
You can drop the `quazip` patch.

**Comment by corecontingency** [comment]
Just cleaned up the commit history.

**Comment by corecontingency** [comment]
Pull request superseded by #56 .

**Pull request closed without merging**
