### PR TITLE
update_ver_2.6.6

### PR DESCRIPTION
**Pull request by superuser-miguel**

### CODE REVIEW

**Comment by akallabeth** [comment]
@superuser-miguel I´ve already done this in #83 but the repo maintainer seems to be inactive since february...

**Comment by superuser-miguel** [comment]
@akallabeth  Yeah I saw that, sorry. I clicked the link of your merge and it was dead, so I decided to try. I'm wondering i fwe can publish the app to flathub instead that way the app stays in active development ⁉️

**Comment by hfiguiere** [comment]
closed with #83 


This PR didn't remove the patch.

**Comment by superuser-miguel** [comment]
@akallabeth Join the https://discourse.flathub.org/ forum incase this happens again, you can redirect issues with abandoned packages.

**Pull request closed without merging**
