### PR TITLE
keepassxc 2.6.4

### PR DESCRIPTION
**Pull request by lunaryorn**

### CODE REVIEW

**Comment by AsavarTzeth** [comment]
I am actually working on this currently, because it requires some patch reworks.

**Comment by lunaryorn** [comment]
@AsavarTzeth Oh sorry, didn't want to rush ahead.  I'll leave this be then?

**Comment by AsavarTzeth** [comment]
No problem. In general I greatly appreciate these pull requests and most of the time it works out fine.

I have opened my own pull request now. I ran out of time yesterday.

**Comment by AsavarTzeth** [comment]
Closing in favour of #77

Thank you for your engagement!

**Comment by AsavarTzeth** [comment]
By the way, you don't happen to run a desktop environment with work indicators? I would like that tested but my gnome desktop extension is broken for whatever reason.

**Comment by lunaryorn** [comment]
My indicators work in Gnome; I've got a keepassxc tray icon:

grafik

Gnome 3.38.3 on Fedora & Wayland.

**Comment by AsavarTzeth** [comment]
Lovely! And this works with 2.6.4 as well?

**Pull request closed without merging**
